### ISSUE TITLE
Java 16 Corretto Image

### ISSUE THREAD

**Issue by LucidAPs** [Software-Noob/pterodactyl-images#4]
Hello can you please provide a Java 16 Corretto image aswell? I hope you can do that.

**Comment by Software-Noob** [comment]
I'll take a look into this tomorrow.

**Comment by Software-Noob** [comment]
AWS team does not release Debian-based images at this moment besides the source from which to built.  I'm not a fan of alpine myself as it has many issues with plugins and mods due to the use of musl libc instead of glibc library.

I can take another look into it when they decide to publish Debian images.

**Comment by ggdorman** [comment]
Hi, I'm also interested in an Alpine-based image. Would you still consider doing it? I tried making my own egg but it only half works so it would be great to get some help.
Also, mind giving some insight into the problems with mods/plugins on Alpine. I can't seen to find any info on that.

Many thanks,
Gordon

**Comment by Software-Noob** [comment]
Amazon corretto images have been added https://github.com/Software-Noob/pterodactyl-images/commit/065be1e2e28faea5bd7a95d16a7811bd9c32bdd8
